### ISSUE TITLE
Felhasználók mentése és logolása

### ISSUE THREAD

**Issue by abelkocsis** [thebalu/STEv2#1]
@thebalu @kervantas Vagy ez működik? Én cloneoltam herokuból a dolgokat, de nem láttam az adatbázisban bármi ilyesmit.

**Comment by thebalu** [comment]
Nem tudom, hogy az adatbázis hogy működik pontosan, de simán elképzelhető, hogy azt nem tudod így letölteni.
Elvileg működik, mert különben nem tudna új felhasználó írni a botnak (illetve az nem válaszolna).
@kervantas ?

**Comment by meszaroszoltan** [comment]
A dbAPI.js/newUser method tudja hozzá adni a usereket az adatbázishoz. Szerintem egyik webhook sem használja most ezt, így valószínűleg nem logolunk most/még.

**Comment by meszaroszoltan** [comment]
bár az egyik postback csinál ilyesmit (db.newUser(sender_psid);)
akkor lehet mégis működik :D

**Comment by abelkocsis** [comment]
Lehet, hogy a felhasználó mentése működik, de utána én simán kikapom uazt a kérdést

**Comment by thebalu** [comment]
mindig felül írod nem?
