### ISSUE TITLE
`Masikat kerek` gomb tenyleg masikat adjon

### ISSUE THREAD

**Issue by thebalu** [thebalu/STEv2#10]
trivi megoldas: leptetjuk a szamlalot
bonyi megoldas: meg is jegyezzuk, hogy az adott challenget skippelte

**Comment by meszaroszoltan** [comment]
Ezt szerintem fixálja, a getNextTipForUser.

**Comment by abelkocsis** [comment]
Nálam még mindig rossz.

**Comment by kervantas** [comment]
a handlers 96. sorában a ```nextTip = await db.getNextTipForUser(sender_psid);``` milyen id-t ad

**Comment by kervantas** [comment]
plo

**Comment by meszaroszoltan** [comment]
Deployolva lett herokura a tegnapi commit?
Érdemes lenne elgondolkni valami CI/CD piplelieon, hogy nem kelljen manuláisan herokuzni állandóan

**Comment by abelkocsis** [comment]
Akkor nem tudom, de ha máskor nem, most igen, és működik is.

**Comment by meszaroszoltan** [comment]
Mármint a másikat kérek gomb működik?
