### ISSUE TITLE
Tippek angolul

### ISSUE THREAD

**Issue by thebalu** [thebalu/STEv2#21]

**Comment by thebalu** [comment]
Lefordítottam, description_en mezőben van

**Comment by abelkocsis** [comment]
getString már a megfelelőt állítja be. Második paramétere a user nyelve.
Legtöbb dolgot átírtam a templateString-be, és szinte mindent a generateString segítségével kérünk már le.
User language fieldjében tároljuk a nyelvét.

**Comment by abelkocsis** [comment]
További toDo: long_intro lefordítani, kihívások címet is lefordítani, illetve a handleMessage-en belüli seringeket is genetikussá tenni.

**Comment by abelkocsis** [comment]
maybeShowProgress: angol, pipa
