### ISSUE TITLE
Leiratkozás

### ISSUE THREAD

**Issue by abelkocsis** [thebalu/STEv2#4]
Egy bizonyos üzenet, amit elküldve leiratkozhat a user.
Ezt tudomásul kell adnunk neki a legelején, és minden alkalommal, amikor automatikusan "zaklatjuk".

**Comment by thebalu** [comment]
szerintem mondjuk ha mindig elküldjük az nagyon lerontja az experiencet, jobb lenne az elején + néhány naponta. vagy menübe tenni.

**Comment by thebalu** [comment]
egyelőre lezárom, `leiratkozás` szóra leiratkozik, és vissza lehet újra. majd ha random zaklatjuk az embert, akkor gondolkozunk rajta, hgy mikor jelezzük a leiratkozást
