### ISSUE TITLE
Handlerek átírása async kompatibilissé

### ISSUE THREAD

**Issue by thebalu** [thebalu/STEv2#7]
A db api megváltozott, mostmár async a legtöbb művelet.
Ennek megfelelően át kell írni a handlers.js-t.
@kervantas csak a get metódusok asyncek? A set sync módon működik, ugye?

**Comment by meszaroszoltan** [comment]
Igen, csak a get-ek lettek async fucntionok.

/* Valószínűleg az összes Firestore db hívás asyc, csak mivel a set-ek esetében nem akarom megvárni az eredményt - mert minek - ezért ott nincs await, tehát nem kell az async. */

**Comment by thebalu** [comment]
https://twitter.com/ryanflorence/status/1105965243837046784?lang=en
