### ISSUE TITLE
instant üzenet endpoint

### ISSUE THREAD

**Issue by thebalu** [thebalu/STEv2#8]

**Comment by thebalu** [comment]
Kész van a v1, működése:
POST request:  http://savetheearth.herokuapp.com/instant_message
bodyban:
```
{
	"secret": "NAGYONTITKOSJELSZO",
        "users" : ['123456789','234567891']   // optional, if not given, sends it to everyone
	"message":{ ... }
}
```
TODO: Az adatbázissal nem boldogultam. @kervantas a handlers/sendInstantMessage-ben az `users = ['2572117989520100', '2707581762588340']` helyett le kéne kérni az adatbázisból az összes user ID-t

**Comment by abelkocsis** [comment]
Ha meglesz, @kervantas  és @thebalu , zárjuk le az issue-t, hogy áttekinthetőek legyenek a feladatok.
